### ISSUE TITLE
Problem with projections (EPSG), unable to read 'gcs.csv'

### ISSUE THREAD

**Issue by ewirth** [developmentseed/geolambda#92]
Having this error in Logging:
_Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files._

Corresponding code parts:
```python
# imports used for the example code below
import logging
from osgeo import gdal
from osgeo import ogr
from osgeo import osr
epsg_in = 4326
osr_in = osr.SpatialReference()
osr_in.ImportFromEPSG(epsg_in)
```
But if check the geolambda layer, I can find the gcs.csv file in share/gdal folder.
Already tried with the setting of Environmental variable at Lambda function (key: GDAL_DATA, value: /usr/local/share/gdal) but nothing changed :S  
What can be the reason of this? Any idea how to fix it?

Additional: Tried with these as well, didn't work:
"GDAL_DATA": "/opt/share/gdal",
"PROJ_LIB": "/opt/share/proj",

**Comment by matthewhanson** [comment]
@ewirth sorry this was never responded to this, this whole repo has gone unattended. But I'm working on some updates, did you ever resolve this?  It seems like it should have been solved with the GDAL_DATA envvar.

**Comment by ewirth** [comment]
@matthewhanson no worries :), basically I 'solved' it with a detour: I read the projections from existing layers.
I tried to update the environmental variables with import os, etc.; but I couldn't fix it.

**Comment by MrSpark2591** [comment]
I am facing same issue any solution. I have set `"GDAL_DATA": "/opt/share/gdal",
"PROJ_LIB": "/opt/share/proj"`. But still getting the issue.

**Comment by ervinw** [comment]
I guess it should be closed... The problem still exist..
